# Site setings
name: 'Max Makes Stuff!'
description: 'Graphics, Games and Interactive Design'
# Sidebar about text
site_description: 'Hello! I am Max van der Merwe! A Programmer, Designer and Technical Artist working primarily on video games!'
logo:
favicon:
production_url: www.linkedin.com/in/james-max-van-der-merwe-5b2558251
disqus: 
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: maxvdm@gmail.com
contact_page_description: ""
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'maxvandm'
linkedin: 'james-max-van-der-merwe-5b2558251'


# Navigation
navigation:
  - text: About
    url: /about/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-author-page

# Pagination
paginate: 7
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
